project_id = "xqfivoqvgdkwsrgrqfld"

[functions.send-push-notification]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.admin-operations]
verify_jwt = false

[functions.create-student-with-parent]
verify_jwt = false

[functions.login-by-name]
verify_jwt = false

[functions.toggle-user-status]
verify_jwt = false
